### ISSUE TITLE
Unable to build OEMUnlock module in Powershell

### ISSUE THREAD

**Issue by Bungeetaco** [chenxiaolong/avbroot#104]
Getting the following error message when trying to build the OEMUnlockOnBoot module. I am running Windows 11 with the latest version of Python installed (3.11.4) and the latest Android Studio version installed with the ANDROID_HOME variable set to the correct SDK folder:

> PS C:\Users\BNGEE\Desktop\Files\avbroot> python .\modules\build.py
Built module C:\Users\BNGEE\Desktop\Files\avbroot\modules\dist\clearotacerts-1.0.zip
Traceback (most recent call last):
  File "C:\Users\BNGEE\Desktop\Files\avbroot\modules\build.py", line 164, in <module>
    main()
  File "C:\Users\BNGEE\Desktop\Files\avbroot\modules\build.py", line 150, in main
    'data': build_dex([os.path.join(module_dir, 'Main.java')]),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BNGEE\Desktop\Files\avbroot\modules\build.py", line 62, in build_dex
    subprocess.check_call([
  File "C:\Program Files\Python311\Lib\subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Bungeetaco** [comment]
I can see d8.bat under C:\Users\BNGEE\AppData\Local\Android\Sdk\build-tools\34.0.0

![image](https://github.com/chenxiaolong/avbroot/assets/5958682/2cd14283-0c32-4780-9bcd-45bb5da7859d)


ANDROID_HOME environment variable is set to C:\Users\BNGEE\AppData\Local\Android\Sdk

**Comment by chenxiaolong** [comment]
Thanks, this has been fixed in #105.

**Comment by Bungeetaco** [comment]
Appreciate the quick turnaround, and a huge thank you for maintaining this project!
