### ISSUE TITLE
FileNotFoundError: [WinError 2] System can not find file

### ISSUE THREAD

**Issue by LukasKarer** [chenxiaolong/avbroot#115]
`Passphrase for .\avb.key:
Traceback (most recent call last):
  File "D:\avbroot\avbroot.py", line 6, in <module>
    main.main()
  File "D:\avbroot\avbroot\main.py", line 494, in main
    patch_subcommand(args)
  File "D:\avbroot\avbroot\main.py", line 322, in patch_subcommand
    passphrase_avb = openssl.prompt_passphrase(args.privkey_avb)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\avbroot\avbroot\openssl.py", line 207, in prompt_passphrase
    subprocess.check_output(['openssl', 'pkey', '-in', pkey, '-noout'])
  File "C:\Python311\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\unittest\mock.py", line 1124, in __call__
    return self._mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\unittest\mock.py", line 1128, in _mock_call
    return self._execute_mock_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\unittest\mock.py", line 1189, in _execute_mock_call
    result = effect(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\avbroot\avbroot\openssl.py", line 81, in __call__
    return self.orig_popen(new_cmd, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden`

I sadly have absolutly no idea what is going wrong here, can someone help me? Passphrase is 100% right.

**Comment by LukasKarer** [comment]
Okay, for everyone seeing this in the future, check if oppenssl is properly working for you. That was my problem :D

**Comment by chenxiaolong** [comment]
Thanks for posting the solution! I'm surprised Python's errors are that bad on Windows. On Linux, it looks like this instead:

```
FileNotFoundError: [Errno 2] No such file or directory: 'openssl'
```
