### ISSUE TITLE
KMI compatibility check failed: 5.10-android13-4 -> None

### ISSUE THREAD

**Issue by duament** [chenxiaolong/avbroot#126]
Hi, I'm using a script to repack the boot image with kernelsu for my pixel 7. The script used to work fine. But It failed on the latest kernelsu release (0.6.6). My script and logs are below.

Then I tried to pass 2 `--ignore-prepatched-compat` arguments. Patching. Flashing. Rebooting. Everything seems to work.

So there must be something wrong during the KMI check. I tried to find the string "Linux version" in the kernelsu kernel image and got the following result:
```
Linux version 5.10.157 (build-user@build-host) (Android (8508608, based on r450784e) clang version 14.0.7
```
It does not contains an android version. I'm confused.

#### my script (generated by nix shell)
```bash
#!/nix/store/p6dlr3skfhxpyphipg2bqnj52999banh-bash-5.2-p15/bin/bash
set -o errexit
set -o nounset
set -o pipefail

set -ex
DIR=$(mktemp -d)

/nix/store/f2zvbgwr985gj0402qks4wk1mw30xvdy-python3-3.10.12-env/bin/python /nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot.py extract --input "$1" --directory "$DIR" --boot-only --boot-partition @gki_kernel
/nix/store/njsvpy3hcqvqqrh0wn9wcp3p535rsddh-android-tools-34.0.1/bin/unpack_bootimg --boot_img "$DIR"/boot.img --out "$DIR"/boot --format=mkbootimg > "$DIR"/mkbootimg_args
VERSION=$(strings "$DIR"/boot/kernel | grep -o -m1 'Linux version [^-]*-[^-]*' || true)  # Linux version 5.10.157-android13
ANDROID_RELEASE=${VERSION##*-}  # android13
VERSION=${VERSION%-*}  # Linux version 5.10.157
KERNEL_VERSION=${VERSION##* }  # 5.10.157
URL=$(/nix/store/vrqmjwwzi985fbz7yk2z6r2bzcnpcd8x-jq-1.6-bin/bin/jq < /nix/store/1w43c9x6w1d8yj2jzg21fkyznvn6gqd9-KernelSU-release -r ".assets[] | select(.name | startswith(\"AnyKernel3-$ANDROID_RELEASE-$KERNEL_VERSION\")) | .browser_download_url")

/nix/store/88pqhjpkyk52jpvcsgwkqw7gr5q959ra-curl-8.1.2-bin/bin/curl -Ls -o "$DIR"/KernelSU.zip "$URL"
/nix/store/gmpgfy5vcrfp4yjdyghlcbbn2bw8fj9y-unzip-6.0/bin/unzip "$DIR"/KernelSU.zip Image -d "$DIR"
rm -f "$DIR"/boot/kernel
/nix/store/vynhsiqj0sqlrs5z61r4mhi2g19zi1yg-lz4-1.9.4-bin/bin/lz4 -l "$DIR"/Image "$DIR"/boot/kernel
sh -c "/nix/store/njsvpy3hcqvqqrh0wn9wcp3p535rsddh-android-tools-34.0.1/bin/mkbootimg $(cat "$DIR"/mkbootimg_args) -o \"$DIR\"/repacked.img"

/nix/store/f2zvbgwr985gj0402qks4wk1mw30xvdy-python3-3.10.12-env/bin/python /nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot.py patch --input "$1" --privkey-avb avb.key --privkey-ota ota.key --cert-ota ota.crt --prepatched "$DIR"/repacked.img --boot-partition @gki_kernel

rm -rf "$DIR"
```

#### logs
```
++ mktemp -d
+ DIR=/tmp/tmp.BrklDELGE2
+ /nix/store/f2zvbgwr985gj0402qks4wk1mw30xvdy-python3-3.10.12-env/bin/python /nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot.py extract --input ota/panther-ota-tq3a.230805.001-0a7ebebd.zip --directory /tmp/tmp.BrklDELGE2 --boot-only --boot-partition @gki_kernel
***** Extracting boot from the payload *****
+ /nix/store/njsvpy3hcqvqqrh0wn9wcp3p535rsddh-android-tools-34.0.1/bin/unpack_bootimg --boot_img /tmp/tmp.BrklDELGE2/boot.img --out /tmp/tmp.BrklDELGE2/boot --format=mkbootimg
++ strings /tmp/tmp.BrklDELGE2/boot/kernel
++ grep -o -m1 'Linux version [^-]*-[^-]*'
++ true
+ VERSION='Linux version 5.10.157-android13'
+ ANDROID_RELEASE=android13
+ VERSION='Linux version 5.10.157'
+ KERNEL_VERSION=5.10.157
++ /nix/store/vrqmjwwzi985fbz7yk2z6r2bzcnpcd8x-jq-1.6-bin/bin/jq -r '.assets[] | select(.name | startswith("AnyKernel3-android13-5.10.157")) | .browser_download_url'
+ URL=https://github.com/tiann/KernelSU/releases/download/v0.6.6/AnyKernel3-android13-5.10.157_2023-03.zip
+ /nix/store/88pqhjpkyk52jpvcsgwkqw7gr5q959ra-curl-8.1.2-bin/bin/curl -Ls -o /tmp/tmp.BrklDELGE2/KernelSU.zip https://github.com/tiann/KernelSU/releases/download/v0.6.6/AnyKernel3-android13-5.10.157_2023-03.zip
+ /nix/store/gmpgfy5vcrfp4yjdyghlcbbn2bw8fj9y-unzip-6.0/bin/unzip /tmp/tmp.BrklDELGE2/KernelSU.zip Image -d /tmp/tmp.BrklDELGE2
Archive:  /tmp/tmp.BrklDELGE2/KernelSU.zip
  inflating: /tmp/tmp.BrklDELGE2/Image
+ rm -f /tmp/tmp.BrklDELGE2/boot/kernel
+ /nix/store/vynhsiqj0sqlrs5z61r4mhi2g19zi1yg-lz4-1.9.4-bin/bin/lz4 -l /tmp/tmp.BrklDELGE2/Image /tmp/tmp.BrklDELGE2/boot/kernel
Compressed 43583812 bytes into 25222020 bytes ==> 57.87%
++ cat /tmp/tmp.BrklDELGE2/mkbootimg_args
+ sh -c '/nix/store/njsvpy3hcqvqqrh0wn9wcp3p535rsddh-android-tools-34.0.1/bin/mkbootimg --header_version 4 --kernel /tmp/tmp.BrklDELGE2/boot/kernel --ramdisk /tmp/tmp.BrklDELGE2/boot/ramdisk --cmdline '\'''\'' -o "/tmp/tmp.BrklDELGE2"/repacked.img'
+ /nix/store/f2zvbgwr985gj0402qks4wk1mw30xvdy-python3-3.10.12-env/bin/python /nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot.py patch --input ota/panther-ota-tq3a.230805.001-0a7ebebd.zip --privkey-avb avb.key --privkey-ota ota.key --cert-ota ota.crt --prepatched /tmp/tmp.BrklDELGE2/repacked.img --boot-partition @gki_kernel
Passphrase for avb.key:
Passphrase for ota.key:
***** Copying apex_info.pb *****
***** Copying care_map.pb *****
***** Patching payload.bin *****
***** Extracting boot, vbmeta, vbmeta_system, vbmeta_vendor, vendor_boot from the payload *****
***** Patching boot, vendor_boot *****
Traceback (most recent call last):
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot.py", line 6, in <module>
    main.main()
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/main.py", line 725, in main
    patch_subcommand(args)
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/main.py", line 474, in patch_subcommand
    metadata = patch_ota_zip(args.input, temp, context)
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/main.py", line 375, in patch_ota_zip
    properties = patch_ota_payload(
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/main.py", line 196, in patch_ota_payload
    future.result()
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/nix/store/jhflvwr40xbb0xr6jx4311icp9cym1fp-python3-3.10.12/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/main.py", line 180, in apply_patches
    boot.patch_boot(
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/boot.py", line 444, in patch_boot
    patch_func(f.name)
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/boot.py", line 39, in __call__
    boot_image = self.patch(image_file, boot_image)
  File "/nix/store/y12qnssnp7c0c9gadrkwhbi2zz9d1qw2-source/avbroot/boot.py", line 371, in patch
    raise ValueError('The prepatched boot image is not compatible '
ValueError: The prepatched boot image is not compatible with the original:
- Kernel module interface version changed: 5.10-android13-4 -> None
```

**Comment by chenxiaolong** [comment]
Thanks for the detailed report!

This was a KernelSU 0.6.6 bug https://github.com/tiann/KernelSU/issues/861. It was introduced in https://github.com/tiann/KernelSU/commit/e8a90aadb2c215fbde89d54ef4b5749020cc3819 and fixed in https://github.com/tiann/KernelSU/commit/676590be153372374ef5efb5e84e346627d0f689. In the meantime, you'll have to continue using `--ignore-prepatched-compat --ignore-prepatched-compat` until the next KernelSU release or build the latest KernelSU code from source.
