### ISSUE TITLE
Required python version bounded

### ISSUE THREAD

**Issue by ArtemPisarenko** [chenxiaolong/avbroot#17]
Currently it works on python 3.9.x versions only. No older (because of scripts syntax), no newer (because of modules incompatibilities somewhere in external tools used by scripts). At least, it should be documented to new users to reduce pain :)

**Comment by pascallj** [comment]
It's working fine for me with Python 3.10.6. What errors do you have?

**Comment by ArtemPisarenko** [comment]
> It's working fine for me with Python 3.10.6. What errors do you have?

`Traceback (most recent call last):
  File "/home/artem/Documents/avbroot/./avbroot.py", line 15, in <module>
    from avbroot import ota
  File "/home/artem/Documents/avbroot/avbroot/ota.py", line 16, in <module>
    import ota_from_target_files
  File "/home/artem/Documents/avbroot/avbroot/../external/build/tools/releasetools/ota_from_target_files.py", line 263, in <module>
    import care_map_pb2
  File "/home/artem/Documents/avbroot/avbroot/../external/build/tools/releasetools/care_map_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/usr/lib/python3/dist-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 77, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 672, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 632, in _load_backward_compatible
  File "/usr/lib/python3/dist-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/usr/lib/python3/dist-packages/pkg_resources/_vendor/pyparsing.py", line 943, in <module>
    collections.MutableMapping.register(ParseResults)
AttributeError: module 'collections' has no attribute 'MutableMapping'
`

Python 3.10.9

**Comment by ArtemPisarenko** [comment]
Oops, I've just messed with different python versions. I used deadsnakes ppa on ubuntu and didn't take care that required modules have to be also installed per each python instance. There are no fool protection - it just silently used modules found in search path for default system python. Ahh...
