### ISSUE TITLE
Cannot run script, Missing dependencies or something

### ISSUE THREAD

**Issue by FireRat666** [chenxiaolong/avbroot#2]
Sorry to bother you with this, I have been trying to get this script to work for a while now but I am not sure what steps I need to take in order to have all the files required for the patching step 

I have built GrapheneOS from source for my Pixel 6 Pro
I am able to successfully build signed packages with my own keys
But I don't know how to sign the boot with a custom magisk patched image

I am able to use the avbtool that I found in my graphene build files 
But when I get to the step of patching the OTA, I am missing lots of different files that it's looking for 
Many of them I was able to locate from here https://android.googlesource.com/platform/build/+/master/tools/releasetools
After adding all the dependencies and missing files I could find, I am still unable to run the script without errors of missing things 

Just an explanation of how you setup your build environment or something so that you were able to run the script
I am just not able to replicate it and I don't know what you have done to get all those required files
Any help would be greatly appreciated 

I believe if I can just insert my own custom patched image earlier in the build process of Graphene then I wouldn't even need this script but I can't figure it out, either the image is unpatched or it's inserted too late and not signed

**Comment by chenxiaolong** [comment]
Any chance the git clone doesn't include the submodules? I forgot to mention this in the README. You can either do the initial clone with `git clone --recursive <url>` or if you already have the repo cloned, then `git submodule update --init --recursive`. If it's working properly, the folders under `external/` should not be empty.

The submodules include known working commits of the required AOSP repos, so you shouldn't have to copy files from AOSP/GrapheneOS. The only required system dependencies are a java compiler, openssl, and python 3 (I'll make sure to document this too).

> I believe if I can just insert my own custom patched image earlier in the build process of Graphene then I wouldn't even need this script but I can't figure it out, either the image is unpatched or it's inserted too late and not signed

I think this is the ideal way to go also, although I haven't tried making it work yet.

**Comment by chenxiaolong** [comment]
Thanks for providing the sample keys. They worked for me when running the same `python avbroot.py` command.

I think I might've found the issue though. The failing command is `openssl rsa -in ota.pk8 -noout -modulus` and the `ota.pk8` temporary file is DER-encoded. With openssl 3.0 (what I've been testing against), it automatically detects if the input file is PEM or DER encoded. With openssl 1.1, it seems like an additional `-inform DER` argument is required.

I just pushed commit ee297eb605de1f6794cdb20fdd911e15a2866599, which should hopefully fix this issue.

**Comment by FireRat666** [comment]
Thank you, That has fixed the error at that point, it now begins to work, does some things successfully, and then gives basically the same error as before, Maybe that fix needs to be applied in another location as well?

```
***** Building new root vbmeta image *****
***** Updating OTA payload to reference patched images *****
unable to load Private Key
140261268051776:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
pkeyutl: Error initializing context
Traceback (most recent call last):
  File "/home/owner/avbroottest2/avbroot/avbroot.py", line 299, in <module>
    main()
  File "/home/owner/avbroottest2/avbroot/avbroot.py", line 291, in main
    patch_subcommand(args)
  File "/home/owner/avbroottest2/avbroot/avbroot.py", line 225, in patch_subcommand
    metadata = patch_ota_zip(
  File "/home/owner/avbroottest2/avbroot/avbroot.py", line 172, in patch_ota_zip
    properties = patch_ota_payload(
  File "/home/owner/avbroottest2/avbroot/avbroot.py", line 101, in patch_ota_payload
    return ota.patch_payload(
  File "/home/owner/avbroottest2/avbroot/avbroot/ota.py", line 282, in patch_payload
    dummy_sig = _sign_hash(hashlib.sha256().digest(), key, max_sig_size)
  File "/home/owner/avbroottest2/avbroot/avbroot/ota.py", line 226, in _sign_hash
    hash_signed = openssl.sign_data(key, hash)
  File "/home/owner/avbroottest2/avbroot/avbroot/openssl.py", line 48, in sign_data
    return subprocess.check_output(
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['openssl', 'pkeyutl', '-sign', '-inkey', '/dev/shm/tmpvn32cpjx/ota.pk8', '-pkeyopt', 'digest:sha256']' returned non-zero exit status 1.
[owner@Laptop avbroot]$ 

```

**Comment by FireRat666** [comment]
I updated to openssl 3 like you are using ` OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022) `
and now it works perfectly, so I will close this issue but hope you can still update it to work with openssl 1.1 for others
Thank you

**Comment by chenxiaolong** [comment]
Thanks for the new logs and glad to hear it's working for you with openssl 3. I've pushed one more commit (d965e22875ce2b8639fe67205a747be77c84c772) to fix openssl 1.1 compatibility (tested in an Arch Linux container).
