### ISSUE TITLE
Error while Patching Image: "Unsupported VABC compression: gz"

### ISSUE THREAD

**Issue by 0cwa** [chenxiaolong/avbroot#332]
I have gzip installed, I don't know what VABC is

```
  2.877s  INFO Compressing full image: vendor
  2.877s  INFO Needs updated CoW size estimate: vendor
  2.954s ERROR Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to compress image: vendor
    2: Unsupported VABC compression: gz
Traceback (most recent call last):
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 973, in run
    patch_ota(
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 89, in patch_ota
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['avbroot', 'ota', 'patch', '--input', PosixPath('.tmp/bramble-ota_update-2024080600.zip'), '--output', PosixPath('.tmp/bramble-ota_update-2024080600.patched-dirty.zip'), '--key-avb', PosixPath('avb.key'), '--key-ota', PosixPath('ota.key'), '--cert-ota', PosixPath('ota.crt'), '--rootless', '--replace', 'system', PosixPath('/tmp/tmpyak332u5/images/system.img'), '--replace', 'vendor', PosixPath('/tmp/tmpyak332u5/images/vendor.img'), '--replace', 'vendor_boot', PosixPath('/tmp/tmpyak332u5/images/vendor_boot.img')]' returned non-zero exit status 1.
```

**Comment by chenxiaolong** [comment]
Moving this to the avbroot repo since the limitation is there.

**Comment by chenxiaolong** [comment]
```
    2: Unsupported VABC compression: gz
```

Can you please link to the OTA that you're patching? I haven't encountered any OTA that uses gzip compression for VABC.

**Comment by chenxiaolong** [comment]
VABC is virtual A/B compression. There are a lot of technical details in [Google's docs](https://source.android.com/docs/core/ota/virtual_ab), but the gist of it is this:

Newer devices don't actually have separate A/B partitions for most of the OS because it wastes too much space. On devices that use virtual A/B, when flashing an OTA, the new data gets written to a temporary compressed COW (copy-on-write) volume. This volume is layered on top of empty space on the `super` and `userdata` partitions. After the OTA is installed and the device is able to successfully reboot, this data is merged back into the actual partitions and the space is freed up.

Android needs to know the amount of space necessary for this temporary COW volume ahead of time because it cannot grow. During patching, avbroot computes a new size estimate and it does so by trying to compress the data itself to see how big it is. On all of my devices, VABC uses LZ4 compression, but it looks like your device uses gzip.

gzip compression is something that will need to be supported in avbroot itself. The system gzip installation is not used.

**Comment by 0cwa** [comment]
Thank you for the through explaination.  I am using [GrapheneOS's current stable release for bramble.](https://releases.grapheneos.org/bramble-ota_update-2024080600.zip)

**Comment by chenxiaolong** [comment]
Support for gzip compression for VABC has been added in #333, which will be included in avbroot 3.6.0.

**Comment by 0cwa** [comment]
Amazing! Thank you!

**Comment by pixincreate** [comment]
```
 0.640s  INFO Extracting from original payload: vbmeta
  0.640s  INFO Opening external image: system: "/tmp/tmpzssgzgsq/images/system.img"
  0.640s  INFO Opening external image: vendor: "/tmp/tmpzssgzgsq/images/vendor.img"
  0.640s  INFO Patching boot images: boot, vendor_boot
  2.079s  INFO Patching system image: system
 22.489s  INFO Patched otacerts.zip offsets in system: [639983616..639985571]
 22.489s  INFO Patching vbmeta images: vbmeta
 22.503s  INFO Compressing full image: vendor_boot
 25.433s  INFO Compressing full image: boot
 28.059s  INFO Compressing full image: vendor
 28.059s  INFO Needs updated CoW size estimate: vendor
 28.320s ERROR Failed to patch OTA zip
Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to compress image: vendor
    2: Unsupported VABC compression: gz
Stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
Traceback (most recent call last):
  File "/home/runner/work/pixeneos_test/pixeneos_test/.tmp/tools/my-avbroot-setup/patch.py", line 1012, in <module>
    main()
  File "/home/runner/work/pixeneos_test/pixeneos_test/.tmp/tools/my-avbroot-setup/patch.py", line 1003, in main
    run(args, Path(temp_dir))
  File "/home/runner/work/pixeneos_test/pixeneos_test/.tmp/tools/my-avbroot-setup/patch.py", line 976, in run
    patch_ota(
  File "/home/runner/work/pixeneos_test/pixeneos_test/.tmp/tools/my-avbroot-setup/patch.py", line 92, in patch_ota
    subprocess.check_call(cmd)
  File "/opt/hostedtoolcache/Python/3.12.4/x64/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['avbroot', 'ota', 'patch', '--pass-avb-env-var', 'PASSPHRASE_AVB', '--pass-ota-env-var', 'PASSPHRASE_OTA', '--input', PosixPath('.tmp/bluejay-ota_update-2024080600.zip'), '--output', PosixPath('.tmp/bluejay-ota_update-2024080600.patched.zip'), '--key-avb', PosixPath('.tmp/keys/avb.key'), '--key-ota', PosixPath('.tmp/keys/ota.key'), '--cert-ota', PosixPath('.tmp/keys/ota.crt'), '--magisk', '.tmp/modules/magisk.apk', '--magisk-preinit-device', 'sda8', '--replace', 'system', PosixPath('/tmp/tmpzssgzgsq/images/system.img'), '--replace', 'vendor', PosixPath('/tmp/tmpzssgzgsq/images/vendor.img'), '--replace', 'vendor_boot', PosixPath('/tmp/tmpzssgzgsq/images/vendor_boot.img')]' returned non-zero exit status 1.
```

looks like `bluejay` uses `gz` too. Updating to `v3.6.0`

**Comment by 0cwa** [comment]
@pixincreate Your script did work with bramble, after I updated to 3.6.0 🙂

**Comment by oposums** [comment]
2: Unsupported VABC compression: gz
Regarding this error, it appeared after version 3.2.3, it disappeared on version 3.6.0.
I used version 3.2.3 and this problem did not occur.
