### ISSUE TITLE
Ramdisk size incorrect for bluejay images

### ISSUE THREAD

**Issue by pascallj** [chenxiaolong/avbroot#42]
Since #37, bluejay (Pixel 6a) images are not patched correctly. Tested both January and February images. I get the following error:

```
***** Copying apex_info.pb *****
***** Copying care_map.pb *****
***** Patching payload.bin *****
***** Extracting vbmeta, boot, vendor_boot from the payload *****
***** Patching boot, vendor_boot *****
Traceback (most recent call last):
  File "/home/pascal/avbroot_home/avbroot/avbroot.py", line 352, in <module>
    main()
  File "/home/pascal/avbroot_home/avbroot/avbroot.py", line 344, in main
    patch_subcommand(args)
  File "/home/pascal/avbroot_home/avbroot/avbroot.py", line 274, in patch_subcommand
    metadata = patch_ota_zip(
  File "/home/pascal/avbroot_home/avbroot/avbroot.py", line 212, in patch_ota_zip
    properties = patch_ota_payload(
  File "/home/pascal/avbroot_home/avbroot/avbroot.py", line 101, in patch_ota_payload
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pascal/avbroot_home/avbroot/avbroot.py", line 87, in apply_patches
    boot.patch_boot(
  File "/home/pascal/avbroot_home/avbroot/avbroot/boot.py", line 231, in patch_boot
    patch_func(f.name)
  File "/home/pascal/avbroot_home/avbroot/avbroot/boot.py", line 39, in __call__
    self.patch(image_file, boot_image)
  File "/home/pascal/avbroot_home/avbroot/avbroot/boot.py", line 60, in patch
    self._patch(image_file, boot_image, zip)
  File "/home/pascal/avbroot_home/avbroot/avbroot/boot.py", line 68, in _patch
    entries, ramdisk_format = _load_ramdisk(boot_image.ramdisks[0])
IndexError: list index out of range
```

This does not happen for cheetah. 

`boot_image` contains the following:
```
Boot image v4 header:
- Kernel size:    24884567
- Ramdisk size:   0
- OS version:     0x0
- Reserved:       00000000000000000000000000000000
- Kernel cmdline: b''
```

It seems there is something wrong with the sizes, because instead of ramdisk size, it reports kernel size. And the size doesn't seem legit anyway. It's much bigger than you would expect.

**Comment by chenxiaolong** [comment]
Thanks, I will take a look today (and add bluejay to my testing list for future commits).

**Comment by chenxiaolong** [comment]
OK, bluejay is interesting. There is indeed no ramdisk in `boot`. Previously with magiskboot, a new ramdisk was generated from scratch, containing nothing but magisk's own files. Looking at [Android's docs](https://source.android.com/docs/core/architecture/partitions/vendor-boot-partitions#bootloader-support), this works because:

> The bootloader must load the generic ramdisk into memory immediately following the vendor ramdisk (the CPIO, Gzip, and lz4 formats support this type of concatenation). Do not page align the generic ramdisk image or introduce any other space between it and the end of the vendor ramdisk in memory. After the kernel decompresses, it extracts the concatenated file into an initramfs, which results in a file structure that's a generic ramdisk overlaid on the vendor ramdisk file structure.

So after patching, both `vendor_boot` and `boot` contains `/init`, but `boot`'s version containing Magisk's `/init` has precedence. I will add support for this to match magiskboot's behavior.

**Comment by pascallj** [comment]
That's interesting. Thank you very much. Yeah I was confused because the cheetah images don't report a kernel size (or again I didn't look good enough), but only a ramdisk size. So I was testing if the sizes somehow got swapped.
