### ISSUE TITLE
Magisk rules extract steps do not work (CalyxOS)

### ISSUE THREAD

**Issue by bugsyb** [chenxiaolong/avbroot#83]
Going through steps to extract Magisk rules - it doesn't work. It might be me being a noob or images as these are CalyxOS.
Payload.bin exists in OTA.

avbroot version - git version as of today.

When run on OTA
```
/avbroot.py extract --input /hostfs/media-o/raven-incremental-23407030-23407040.zip --directory ../../ --boot-only
Traceback (most recent call last):
  File "/hostfs/ssd/magisk/avbroot/./avbroot.py", line 6, in <module>
    main.main()
  File "/hostfs/ssd/magisk/avbroot/avbroot/main.py", line 463, in main
    extract_subcommand(args)
  File "/hostfs/ssd/magisk/avbroot/avbroot/main.py", line 345, in extract_subcommand
    _, manifest, blob_offset = ota.parse_payload(f)
  File "/hostfs/ssd/magisk/avbroot/avbroot/ota.py", line 60, in parse_payload
    raise Exception('File is a delta OTA, not a full OTA')
```

When run on full image
```
Traceback (most recent call last):
  File "/hostfs/ssd/magisk/avbroot/./avbroot.py", line 6, in <module>
    main.main()
  File "/hostfs/ssd/magisk/avbroot/avbroot/main.py", line 463, in main
    extract_subcommand(args)
  File "/hostfs/ssd/magisk/avbroot/avbroot/main.py", line 342, in extract_subcommand
    info = z.getinfo(PATH_PAYLOAD)
  File "/usr/lib/python3.10/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'payload.bin' in the archive"

```

**Comment by bugsyb** [comment]
Self close - mistakenly used - factory image and _incremental_OTA_ which avbroot nicely informed (noob + late night doesn't help).
Full OTAs are below: https://calyxos.org/get/ota/
