### ISSUE TITLE
avbtool.AvbError: Key is wrong size for algorithm SHA256_RSA2048

### ISSUE THREAD

**Issue by powellnorma** [chenxiaolong/avbroot#9]
When generating keys with `openssl genrsa 4096` as written in the README.md, I later get this error: 

```python
Traceback (most recent call last):
  File "/avbroot/avbroot.py", line 308, in <module>
    main()
  File "/avbroot/avbroot.py", line 300, in main
    patch_subcommand(args)
  File "/avbroot/avbroot.py", line 234, in patch_subcommand
    metadata = patch_ota_zip(
               ^^^^^^^^^^^^^^
  File "/avbroot/avbroot.py", line 181, in patch_ota_zip
    properties = patch_ota_payload(
                 ^^^^^^^^^^^^^^^^^^
  File "/avbroot/avbroot.py", line 101, in patch_ota_payload
    vbmeta.patch_vbmeta_root(
  File "/avbroot/avbroot/vbmeta.py", line 114, in patch_vbmeta_root
    avb.make_vbmeta_image(
  File "/avbroot/avbroot/../external/avb/avbtool.py", line 2971, in make_vbmeta_image
    vbmeta_blob = self._generate_vbmeta_blob(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/avbroot/avbroot/../external/avb/avbtool.py", line 3170, in _generate_vbmeta_blob
    raise AvbError('Key is wrong size for algorithm {}'.format(
avbtool.AvbError: Key is wrong size for algorithm SHA256_RSA2048
```

It expects  520, but gets 1032 - When I use `openssl genrsa 2048` instead, it succeeds. Maybe somewhere a default value is used, that is different depending on the used distro/OS?

**Comment by chenxiaolong** [comment]
Ah shoot, I fixed this for signing boot images in 163540b2b68a0aa0123c413ed776be9405f65571, but not for signing the vbmeta image. Should be a quick fix.
